services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=multikino'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=toor'
      - 'MYSQL_USER=spring'
      - 'MYSQL_TCP_PORT=3307'
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - multikino:/var/lib/prod
volumes:
  multikino: