spring:
  application:
    name=Multikino
  jpa:
    hibernate.ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3307/multikino
    username: spring
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true